[package]
name = "MyCloudAPI"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = "0.5.1"
diesel = { version = "2.2.0", features = ["mysql"] }
dotenvy = "0.15"
bindgen = "0.69.4"
mysqlclient-sys = { version = "0.3.1", features = ["buildtime_bindgen"] }
